---

- name: Clone tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ tmux_home }}/plugins/tpm"

- name: Check tmux version
  shell: tmux -V | cut -d ' ' -f 2
  register: tmux_register_version
  changed_when: false

- name: Set tmux_version variable
  set_fact:
    tmux_version: "{{ tmux_register_version.stdout }}"

- debug:
    msg: "Installed tmux version {{ tmux_version }}."

- name: Write .tmux.conf config
  template:
    src: tmux.j2
    dest: "{{ tmux_config }}"
    owner: "{{ tmux_user }}"
    group: "{{ tmux_user_group }}"
    backup: "yes"

- name: Install tmux plugins with tpm
  shell: "{{ tmux_home}}/plugins/tpm/bin/install_plugins"
  register: tmux_tpm_install_plugins_out
  changed_when: "'Installing' in tmux_tpm_install_plugins_out.stdout"

- debug:
    msg: "Install plugins output: {{ tmux_tpm_install_plugins_out }}"
